# Site settings
title: Macraris Excel
email: macraris@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Spazio virtuale per imparare Excel 2013 dove puoi arricchire le tue conoscenze con esempi pratici
  acquisire gradualmente la conoscenza di Excel e goderti con allegria il tuo lavoro.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.macraris.com" # the base hostname & protocol for your site
twitter_username: macraris
github_username:  macraris

# Build settings
markdown: kramdown
